//! Port of the upstream test suite (test.js, mocha) for pluralize
//! v8.0.0: 656 singular/plural pairs plus the custom-rule
//! tests. The "prepend count" tests are covered by `count`.

const std = @import("std");
const pl = @import("root.zig");

const t = std.testing;

const Pair = struct { single: []const u8, plural: []const u8 };

const pairs = [_]Pair{
    .{ .single = "firmware", .plural = "firmware" },
    .{ .single = "fish", .plural = "fish" },
    .{ .single = "media", .plural = "media" },
    .{ .single = "moose", .plural = "moose" },
    .{ .single = "police", .plural = "police" },
    .{ .single = "sheep", .plural = "sheep" },
    .{ .single = "series", .plural = "series" },
    .{ .single = "agenda", .plural = "agenda" },
    .{ .single = "news", .plural = "news" },
    .{ .single = "reindeer", .plural = "reindeer" },
    .{ .single = "starfish", .plural = "starfish" },
    .{ .single = "smallpox", .plural = "smallpox" },
    .{ .single = "tennis", .plural = "tennis" },
    .{ .single = "chickenpox", .plural = "chickenpox" },
    .{ .single = "shambles", .plural = "shambles" },
    .{ .single = "garbage", .plural = "garbage" },
    .{ .single = "you", .plural = "you" },
    .{ .single = "wildlife", .plural = "wildlife" },
    .{ .single = "Staff", .plural = "Staff" },
    .{ .single = "STAFF", .plural = "STAFF" },
    .{ .single = "turquois", .plural = "turquois" },
    .{ .single = "carnivorous", .plural = "carnivorous" },
    .{ .single = "only", .plural = "only" },
    .{ .single = "aircraft", .plural = "aircraft" },
    .{ .single = "veniam", .plural = "veniam" },
    .{ .single = "this", .plural = "these" },
    .{ .single = "that", .plural = "those" },
    .{ .single = "is", .plural = "are" },
    .{ .single = "man", .plural = "men" },
    .{ .single = "superman", .plural = "supermen" },
    .{ .single = "ox", .plural = "oxen" },
    .{ .single = "bus", .plural = "buses" },
    .{ .single = "airbus", .plural = "airbuses" },
    .{ .single = "railbus", .plural = "railbuses" },
    .{ .single = "wife", .plural = "wives" },
    .{ .single = "guest", .plural = "guests" },
    .{ .single = "thing", .plural = "things" },
    .{ .single = "mess", .plural = "messes" },
    .{ .single = "guess", .plural = "guesses" },
    .{ .single = "person", .plural = "people" },
    .{ .single = "meteor", .plural = "meteors" },
    .{ .single = "chateau", .plural = "chateaus" },
    .{ .single = "lap", .plural = "laps" },
    .{ .single = "cough", .plural = "coughs" },
    .{ .single = "death", .plural = "deaths" },
    .{ .single = "coach", .plural = "coaches" },
    .{ .single = "boy", .plural = "boys" },
    .{ .single = "toy", .plural = "toys" },
    .{ .single = "guy", .plural = "guys" },
    .{ .single = "girl", .plural = "girls" },
    .{ .single = "chair", .plural = "chairs" },
    .{ .single = "toe", .plural = "toes" },
    .{ .single = "tiptoe", .plural = "tiptoes" },
    .{ .single = "tomato", .plural = "tomatoes" },
    .{ .single = "potato", .plural = "potatoes" },
    .{ .single = "tornado", .plural = "tornadoes" },
    .{ .single = "torpedo", .plural = "torpedoes" },
    .{ .single = "hero", .plural = "heroes" },
    .{ .single = "superhero", .plural = "superheroes" },
    .{ .single = "volcano", .plural = "volcanoes" },
    .{ .single = "canto", .plural = "cantos" },
    .{ .single = "hetero", .plural = "heteros" },
    .{ .single = "photo", .plural = "photos" },
    .{ .single = "portico", .plural = "porticos" },
    .{ .single = "quarto", .plural = "quartos" },
    .{ .single = "kimono", .plural = "kimonos" },
    .{ .single = "albino", .plural = "albinos" },
    .{ .single = "cherry", .plural = "cherries" },
    .{ .single = "piano", .plural = "pianos" },
    .{ .single = "pro", .plural = "pros" },
    .{ .single = "combo", .plural = "combos" },
    .{ .single = "turbo", .plural = "turbos" },
    .{ .single = "bar", .plural = "bars" },
    .{ .single = "crowbar", .plural = "crowbars" },
    .{ .single = "van", .plural = "vans" },
    .{ .single = "tobacco", .plural = "tobaccos" },
    .{ .single = "afficionado", .plural = "afficionados" },
    .{ .single = "monkey", .plural = "monkeys" },
    .{ .single = "neutrino", .plural = "neutrinos" },
    .{ .single = "rhino", .plural = "rhinos" },
    .{ .single = "steno", .plural = "stenos" },
    .{ .single = "latino", .plural = "latinos" },
    .{ .single = "casino", .plural = "casinos" },
    .{ .single = "avocado", .plural = "avocados" },
    .{ .single = "commando", .plural = "commandos" },
    .{ .single = "tuxedo", .plural = "tuxedos" },
    .{ .single = "speedo", .plural = "speedos" },
    .{ .single = "dingo", .plural = "dingoes" },
    .{ .single = "echo", .plural = "echoes" },
    .{ .single = "nacho", .plural = "nachos" },
    .{ .single = "motto", .plural = "mottos" },
    .{ .single = "psycho", .plural = "psychos" },
    .{ .single = "poncho", .plural = "ponchos" },
    .{ .single = "pass", .plural = "passes" },
    .{ .single = "ghetto", .plural = "ghettos" },
    .{ .single = "mango", .plural = "mangos" },
    .{ .single = "lady", .plural = "ladies" },
    .{ .single = "bath", .plural = "baths" },
    .{ .single = "professional", .plural = "professionals" },
    .{ .single = "dwarf", .plural = "dwarves" },
    .{ .single = "encyclopedia", .plural = "encyclopedias" },
    .{ .single = "louse", .plural = "lice" },
    .{ .single = "roof", .plural = "roofs" },
    .{ .single = "woman", .plural = "women" },
    .{ .single = "formula", .plural = "formulas" },
    .{ .single = "polyhedron", .plural = "polyhedra" },
    .{ .single = "index", .plural = "indices" },
    .{ .single = "matrix", .plural = "matrices" },
    .{ .single = "vertex", .plural = "vertices" },
    .{ .single = "axe", .plural = "axes" },
    .{ .single = "pickaxe", .plural = "pickaxes" },
    .{ .single = "crisis", .plural = "crises" },
    .{ .single = "criterion", .plural = "criteria" },
    .{ .single = "phenomenon", .plural = "phenomena" },
    .{ .single = "addendum", .plural = "addenda" },
    .{ .single = "datum", .plural = "data" },
    .{ .single = "forum", .plural = "forums" },
    .{ .single = "millennium", .plural = "millennia" },
    .{ .single = "alumnus", .plural = "alumni" },
    .{ .single = "medium", .plural = "mediums" },
    .{ .single = "census", .plural = "censuses" },
    .{ .single = "genus", .plural = "genera" },
    .{ .single = "dogma", .plural = "dogmata" },
    .{ .single = "life", .plural = "lives" },
    .{ .single = "hive", .plural = "hives" },
    .{ .single = "kiss", .plural = "kisses" },
    .{ .single = "dish", .plural = "dishes" },
    .{ .single = "human", .plural = "humans" },
    .{ .single = "knife", .plural = "knives" },
    .{ .single = "phase", .plural = "phases" },
    .{ .single = "judge", .plural = "judges" },
    .{ .single = "class", .plural = "classes" },
    .{ .single = "witch", .plural = "witches" },
    .{ .single = "church", .plural = "churches" },
    .{ .single = "massage", .plural = "massages" },
    .{ .single = "prospectus", .plural = "prospectuses" },
    .{ .single = "syllabus", .plural = "syllabi" },
    .{ .single = "viscus", .plural = "viscera" },
    .{ .single = "cactus", .plural = "cacti" },
    .{ .single = "hippopotamus", .plural = "hippopotamuses" },
    .{ .single = "octopus", .plural = "octopuses" },
    .{ .single = "platypus", .plural = "platypuses" },
    .{ .single = "kangaroo", .plural = "kangaroos" },
    .{ .single = "atlas", .plural = "atlases" },
    .{ .single = "stigma", .plural = "stigmata" },
    .{ .single = "schema", .plural = "schemata" },
    .{ .single = "phenomenon", .plural = "phenomena" },
    .{ .single = "diagnosis", .plural = "diagnoses" },
    .{ .single = "mongoose", .plural = "mongooses" },
    .{ .single = "mouse", .plural = "mice" },
    .{ .single = "liturgist", .plural = "liturgists" },
    .{ .single = "box", .plural = "boxes" },
    .{ .single = "gas", .plural = "gases" },
    .{ .single = "self", .plural = "selves" },
    .{ .single = "chief", .plural = "chiefs" },
    .{ .single = "quiz", .plural = "quizzes" },
    .{ .single = "child", .plural = "children" },
    .{ .single = "shelf", .plural = "shelves" },
    .{ .single = "fizz", .plural = "fizzes" },
    .{ .single = "tooth", .plural = "teeth" },
    .{ .single = "thief", .plural = "thieves" },
    .{ .single = "day", .plural = "days" },
    .{ .single = "loaf", .plural = "loaves" },
    .{ .single = "fix", .plural = "fixes" },
    .{ .single = "spy", .plural = "spies" },
    .{ .single = "vertebra", .plural = "vertebrae" },
    .{ .single = "clock", .plural = "clocks" },
    .{ .single = "lap", .plural = "laps" },
    .{ .single = "cuff", .plural = "cuffs" },
    .{ .single = "leaf", .plural = "leaves" },
    .{ .single = "calf", .plural = "calves" },
    .{ .single = "moth", .plural = "moths" },
    .{ .single = "mouth", .plural = "mouths" },
    .{ .single = "house", .plural = "houses" },
    .{ .single = "proof", .plural = "proofs" },
    .{ .single = "hoof", .plural = "hooves" },
    .{ .single = "elf", .plural = "elves" },
    .{ .single = "turf", .plural = "turfs" },
    .{ .single = "craft", .plural = "crafts" },
    .{ .single = "die", .plural = "dice" },
    .{ .single = "penny", .plural = "pennies" },
    .{ .single = "campus", .plural = "campuses" },
    .{ .single = "virus", .plural = "viri" },
    .{ .single = "iris", .plural = "irises" },
    .{ .single = "bureau", .plural = "bureaus" },
    .{ .single = "kiwi", .plural = "kiwis" },
    .{ .single = "wiki", .plural = "wikis" },
    .{ .single = "igloo", .plural = "igloos" },
    .{ .single = "ninja", .plural = "ninjas" },
    .{ .single = "pizza", .plural = "pizzas" },
    .{ .single = "kayak", .plural = "kayaks" },
    .{ .single = "canoe", .plural = "canoes" },
    .{ .single = "tiding", .plural = "tidings" },
    .{ .single = "pea", .plural = "peas" },
    .{ .single = "drive", .plural = "drives" },
    .{ .single = "nose", .plural = "noses" },
    .{ .single = "movie", .plural = "movies" },
    .{ .single = "status", .plural = "statuses" },
    .{ .single = "alias", .plural = "aliases" },
    .{ .single = "memorandum", .plural = "memorandums" },
    .{ .single = "language", .plural = "languages" },
    .{ .single = "plural", .plural = "plurals" },
    .{ .single = "word", .plural = "words" },
    .{ .single = "multiple", .plural = "multiples" },
    .{ .single = "reward", .plural = "rewards" },
    .{ .single = "sandwich", .plural = "sandwiches" },
    .{ .single = "subway", .plural = "subways" },
    .{ .single = "direction", .plural = "directions" },
    .{ .single = "land", .plural = "lands" },
    .{ .single = "row", .plural = "rows" },
    .{ .single = "grow", .plural = "grows" },
    .{ .single = "flow", .plural = "flows" },
    .{ .single = "rose", .plural = "roses" },
    .{ .single = "raise", .plural = "raises" },
    .{ .single = "friend", .plural = "friends" },
    .{ .single = "follower", .plural = "followers" },
    .{ .single = "male", .plural = "males" },
    .{ .single = "nail", .plural = "nails" },
    .{ .single = "sex", .plural = "sexes" },
    .{ .single = "tape", .plural = "tapes" },
    .{ .single = "ruler", .plural = "rulers" },
    .{ .single = "king", .plural = "kings" },
    .{ .single = "queen", .plural = "queens" },
    .{ .single = "zero", .plural = "zeros" },
    .{ .single = "quest", .plural = "quests" },
    .{ .single = "goose", .plural = "geese" },
    .{ .single = "foot", .plural = "feet" },
    .{ .single = "ex", .plural = "exes" },
    .{ .single = "reflex", .plural = "reflexes" },
    .{ .single = "heat", .plural = "heats" },
    .{ .single = "train", .plural = "trains" },
    .{ .single = "test", .plural = "tests" },
    .{ .single = "pie", .plural = "pies" },
    .{ .single = "fly", .plural = "flies" },
    .{ .single = "eye", .plural = "eyes" },
    .{ .single = "lie", .plural = "lies" },
    .{ .single = "node", .plural = "nodes" },
    .{ .single = "trade", .plural = "trades" },
    .{ .single = "chinese", .plural = "chinese" },
    .{ .single = "please", .plural = "pleases" },
    .{ .single = "japanese", .plural = "japanese" },
    .{ .single = "regex", .plural = "regexes" },
    .{ .single = "license", .plural = "licenses" },
    .{ .single = "zebra", .plural = "zebras" },
    .{ .single = "general", .plural = "generals" },
    .{ .single = "corps", .plural = "corps" },
    .{ .single = "pliers", .plural = "pliers" },
    .{ .single = "flyer", .plural = "flyers" },
    .{ .single = "scissors", .plural = "scissors" },
    .{ .single = "fireman", .plural = "firemen" },
    .{ .single = "chirp", .plural = "chirps" },
    .{ .single = "harp", .plural = "harps" },
    .{ .single = "corpse", .plural = "corpses" },
    .{ .single = "dye", .plural = "dyes" },
    .{ .single = "move", .plural = "moves" },
    .{ .single = "zombie", .plural = "zombies" },
    .{ .single = "variety", .plural = "varieties" },
    .{ .single = "talkie", .plural = "talkies" },
    .{ .single = "walkie-talkie", .plural = "walkie-talkies" },
    .{ .single = "groupie", .plural = "groupies" },
    .{ .single = "goonie", .plural = "goonies" },
    .{ .single = "lassie", .plural = "lassies" },
    .{ .single = "genie", .plural = "genies" },
    .{ .single = "foodie", .plural = "foodies" },
    .{ .single = "faerie", .plural = "faeries" },
    .{ .single = "collie", .plural = "collies" },
    .{ .single = "obloquy", .plural = "obloquies" },
    .{ .single = "looey", .plural = "looies" },
    .{ .single = "osprey", .plural = "ospreys" },
    .{ .single = "cover", .plural = "covers" },
    .{ .single = "tie", .plural = "ties" },
    .{ .single = "groove", .plural = "grooves" },
    .{ .single = "bee", .plural = "bees" },
    .{ .single = "ave", .plural = "aves" },
    .{ .single = "wave", .plural = "waves" },
    .{ .single = "wolf", .plural = "wolves" },
    .{ .single = "airwave", .plural = "airwaves" },
    .{ .single = "archive", .plural = "archives" },
    .{ .single = "arch", .plural = "arches" },
    .{ .single = "dive", .plural = "dives" },
    .{ .single = "aftershave", .plural = "aftershaves" },
    .{ .single = "cave", .plural = "caves" },
    .{ .single = "grave", .plural = "graves" },
    .{ .single = "gift", .plural = "gifts" },
    .{ .single = "nerve", .plural = "nerves" },
    .{ .single = "nerd", .plural = "nerds" },
    .{ .single = "carve", .plural = "carves" },
    .{ .single = "rave", .plural = "raves" },
    .{ .single = "scarf", .plural = "scarves" },
    .{ .single = "sale", .plural = "sales" },
    .{ .single = "sail", .plural = "sails" },
    .{ .single = "swerve", .plural = "swerves" },
    .{ .single = "love", .plural = "loves" },
    .{ .single = "dove", .plural = "doves" },
    .{ .single = "glove", .plural = "gloves" },
    .{ .single = "wharf", .plural = "wharves" },
    .{ .single = "valve", .plural = "valves" },
    .{ .single = "werewolf", .plural = "werewolves" },
    .{ .single = "view", .plural = "views" },
    .{ .single = "emu", .plural = "emus" },
    .{ .single = "menu", .plural = "menus" },
    .{ .single = "wax", .plural = "waxes" },
    .{ .single = "fax", .plural = "faxes" },
    .{ .single = "nut", .plural = "nuts" },
    .{ .single = "crust", .plural = "crusts" },
    .{ .single = "lemma", .plural = "lemmata" },
    .{ .single = "anathema", .plural = "anathemata" },
    .{ .single = "analysis", .plural = "analyses" },
    .{ .single = "locus", .plural = "loci" },
    .{ .single = "uterus", .plural = "uteri" },
    .{ .single = "curriculum", .plural = "curricula" },
    .{ .single = "quorum", .plural = "quora" },
    .{ .single = "genius", .plural = "geniuses" },
    .{ .single = "flower", .plural = "flowers" },
    .{ .single = "crash", .plural = "crashes" },
    .{ .single = "soul", .plural = "souls" },
    .{ .single = "career", .plural = "careers" },
    .{ .single = "planet", .plural = "planets" },
    .{ .single = "son", .plural = "sons" },
    .{ .single = "sun", .plural = "suns" },
    .{ .single = "drink", .plural = "drinks" },
    .{ .single = "diploma", .plural = "diplomas" },
    .{ .single = "dilemma", .plural = "dilemmas" },
    .{ .single = "grandma", .plural = "grandmas" },
    .{ .single = "no", .plural = "nos" },
    .{ .single = "yes", .plural = "yeses" },
    .{ .single = "employ", .plural = "employs" },
    .{ .single = "employee", .plural = "employees" },
    .{ .single = "history", .plural = "histories" },
    .{ .single = "story", .plural = "stories" },
    .{ .single = "purchase", .plural = "purchases" },
    .{ .single = "order", .plural = "orders" },
    .{ .single = "key", .plural = "keys" },
    .{ .single = "bomb", .plural = "bombs" },
    .{ .single = "city", .plural = "cities" },
    .{ .single = "sanity", .plural = "sanities" },
    .{ .single = "ability", .plural = "abilities" },
    .{ .single = "activity", .plural = "activities" },
    .{ .single = "cutie", .plural = "cuties" },
    .{ .single = "validation", .plural = "validations" },
    .{ .single = "floaty", .plural = "floaties" },
    .{ .single = "nicety", .plural = "niceties" },
    .{ .single = "goalie", .plural = "goalies" },
    .{ .single = "crawly", .plural = "crawlies" },
    .{ .single = "duty", .plural = "duties" },
    .{ .single = "scrutiny", .plural = "scrutinies" },
    .{ .single = "deputy", .plural = "deputies" },
    .{ .single = "beauty", .plural = "beauties" },
    .{ .single = "bank", .plural = "banks" },
    .{ .single = "family", .plural = "families" },
    .{ .single = "tally", .plural = "tallies" },
    .{ .single = "ally", .plural = "allies" },
    .{ .single = "alley", .plural = "alleys" },
    .{ .single = "valley", .plural = "valleys" },
    .{ .single = "medley", .plural = "medleys" },
    .{ .single = "melody", .plural = "melodies" },
    .{ .single = "trolly", .plural = "trollies" },
    .{ .single = "thunk", .plural = "thunks" },
    .{ .single = "koala", .plural = "koalas" },
    .{ .single = "special", .plural = "specials" },
    .{ .single = "book", .plural = "books" },
    .{ .single = "knob", .plural = "knobs" },
    .{ .single = "crab", .plural = "crabs" },
    .{ .single = "plough", .plural = "ploughs" },
    .{ .single = "high", .plural = "highs" },
    .{ .single = "low", .plural = "lows" },
    .{ .single = "hiccup", .plural = "hiccups" },
    .{ .single = "bonus", .plural = "bonuses" },
    .{ .single = "circus", .plural = "circuses" },
    .{ .single = "abacus", .plural = "abacuses" },
    .{ .single = "phobia", .plural = "phobias" },
    .{ .single = "case", .plural = "cases" },
    .{ .single = "lace", .plural = "laces" },
    .{ .single = "trace", .plural = "traces" },
    .{ .single = "mage", .plural = "mages" },
    .{ .single = "lotus", .plural = "lotuses" },
    .{ .single = "motorbus", .plural = "motorbuses" },
    .{ .single = "cutlas", .plural = "cutlases" },
    .{ .single = "tequila", .plural = "tequilas" },
    .{ .single = "liar", .plural = "liars" },
    .{ .single = "delta", .plural = "deltas" },
    .{ .single = "visa", .plural = "visas" },
    .{ .single = "flea", .plural = "fleas" },
    .{ .single = "favela", .plural = "favelas" },
    .{ .single = "cobra", .plural = "cobras" },
    .{ .single = "finish", .plural = "finishes" },
    .{ .single = "gorilla", .plural = "gorillas" },
    .{ .single = "mass", .plural = "masses" },
    .{ .single = "face", .plural = "faces" },
    .{ .single = "rabbit", .plural = "rabbits" },
    .{ .single = "adventure", .plural = "adventures" },
    .{ .single = "breeze", .plural = "breezes" },
    .{ .single = "brew", .plural = "brews" },
    .{ .single = "canopy", .plural = "canopies" },
    .{ .single = "copy", .plural = "copies" },
    .{ .single = "spy", .plural = "spies" },
    .{ .single = "cave", .plural = "caves" },
    .{ .single = "charge", .plural = "charges" },
    .{ .single = "cinema", .plural = "cinemas" },
    .{ .single = "coffee", .plural = "coffees" },
    .{ .single = "favourite", .plural = "favourites" },
    .{ .single = "themself", .plural = "themselves" },
    .{ .single = "country", .plural = "countries" },
    .{ .single = "issue", .plural = "issues" },
    .{ .single = "authority", .plural = "authorities" },
    .{ .single = "force", .plural = "forces" },
    .{ .single = "objective", .plural = "objectives" },
    .{ .single = "present", .plural = "presents" },
    .{ .single = "industry", .plural = "industries" },
    .{ .single = "believe", .plural = "believes" },
    .{ .single = "century", .plural = "centuries" },
    .{ .single = "category", .plural = "categories" },
    .{ .single = "eve", .plural = "eves" },
    .{ .single = "fee", .plural = "fees" },
    .{ .single = "gene", .plural = "genes" },
    .{ .single = "try", .plural = "tries" },
    .{ .single = "currency", .plural = "currencies" },
    .{ .single = "pose", .plural = "poses" },
    .{ .single = "cheese", .plural = "cheeses" },
    .{ .single = "clue", .plural = "clues" },
    .{ .single = "cheer", .plural = "cheers" },
    .{ .single = "litre", .plural = "litres" },
    .{ .single = "money", .plural = "monies" },
    .{ .single = "attorney", .plural = "attorneys" },
    .{ .single = "balcony", .plural = "balconies" },
    .{ .single = "cockney", .plural = "cockneys" },
    .{ .single = "donkey", .plural = "donkeys" },
    .{ .single = "honey", .plural = "honeys" },
    .{ .single = "smiley", .plural = "smilies" },
    .{ .single = "survey", .plural = "surveys" },
    .{ .single = "whiskey", .plural = "whiskeys" },
    .{ .single = "whisky", .plural = "whiskies" },
    .{ .single = "volley", .plural = "volleys" },
    .{ .single = "tongue", .plural = "tongues" },
    .{ .single = "suit", .plural = "suits" },
    .{ .single = "suite", .plural = "suites" },
    .{ .single = "cruise", .plural = "cruises" },
    .{ .single = "eave", .plural = "eaves" },
    .{ .single = "consultancy", .plural = "consultancies" },
    .{ .single = "pouch", .plural = "pouches" },
    .{ .single = "wallaby", .plural = "wallabies" },
    .{ .single = "abyss", .plural = "abysses" },
    .{ .single = "weekly", .plural = "weeklies" },
    .{ .single = "whistle", .plural = "whistles" },
    .{ .single = "utilise", .plural = "utilises" },
    .{ .single = "utilize", .plural = "utilizes" },
    .{ .single = "mercy", .plural = "mercies" },
    .{ .single = "mercenary", .plural = "mercenaries" },
    .{ .single = "take", .plural = "takes" },
    .{ .single = "flush", .plural = "flushes" },
    .{ .single = "gate", .plural = "gates" },
    .{ .single = "evolve", .plural = "evolves" },
    .{ .single = "slave", .plural = "slaves" },
    .{ .single = "native", .plural = "natives" },
    .{ .single = "revolve", .plural = "revolves" },
    .{ .single = "twelve", .plural = "twelves" },
    .{ .single = "sleeve", .plural = "sleeves" },
    .{ .single = "subjective", .plural = "subjectives" },
    .{ .single = "stream", .plural = "streams" },
    .{ .single = "beam", .plural = "beams" },
    .{ .single = "foam", .plural = "foams" },
    .{ .single = "callus", .plural = "calluses" },
    .{ .single = "use", .plural = "uses" },
    .{ .single = "beau", .plural = "beaus" },
    .{ .single = "gateau", .plural = "gateaus" },
    .{ .single = "fetus", .plural = "fetuses" },
    .{ .single = "luau", .plural = "luaus" },
    .{ .single = "pilau", .plural = "pilaus" },
    .{ .single = "shoe", .plural = "shoes" },
    .{ .single = "sandshoe", .plural = "sandshoes" },
    .{ .single = "zeus", .plural = "zeuses" },
    .{ .single = "nucleus", .plural = "nuclei" },
    .{ .single = "sky", .plural = "skies" },
    .{ .single = "beach", .plural = "beaches" },
    .{ .single = "brush", .plural = "brushes" },
    .{ .single = "hoax", .plural = "hoaxes" },
    .{ .single = "scratch", .plural = "scratches" },
    .{ .single = "nanny", .plural = "nannies" },
    .{ .single = "negro", .plural = "negroes" },
    .{ .single = "taco", .plural = "tacos" },
    .{ .single = "cafe", .plural = "cafes" },
    .{ .single = "cave", .plural = "caves" },
    .{ .single = "giraffe", .plural = "giraffes" },
    .{ .single = "goodwife", .plural = "goodwives" },
    .{ .single = "housewife", .plural = "housewives" },
    .{ .single = "safe", .plural = "safes" },
    .{ .single = "save", .plural = "saves" },
    .{ .single = "pocketknife", .plural = "pocketknives" },
    .{ .single = "tartufe", .plural = "tartufes" },
    .{ .single = "tartuffe", .plural = "tartuffes" },
    .{ .single = "truffle", .plural = "truffles" },
    .{ .single = "jefe", .plural = "jefes" },
    .{ .single = "agrafe", .plural = "agrafes" },
    .{ .single = "agraffe", .plural = "agraffes" },
    .{ .single = "bouffe", .plural = "bouffes" },
    .{ .single = "carafe", .plural = "carafes" },
    .{ .single = "chafe", .plural = "chafes" },
    .{ .single = "pouffe", .plural = "pouffes" },
    .{ .single = "pouf", .plural = "poufs" },
    .{ .single = "piaffe", .plural = "piaffes" },
    .{ .single = "gaffe", .plural = "gaffes" },
    .{ .single = "executive", .plural = "executives" },
    .{ .single = "cove", .plural = "coves" },
    .{ .single = "dove", .plural = "doves" },
    .{ .single = "fave", .plural = "faves" },
    .{ .single = "positive", .plural = "positives" },
    .{ .single = "solve", .plural = "solves" },
    .{ .single = "trove", .plural = "troves" },
    .{ .single = "treasure", .plural = "treasures" },
    .{ .single = "suave", .plural = "suaves" },
    .{ .single = "bluff", .plural = "bluffs" },
    .{ .single = "half", .plural = "halves" },
    .{ .single = "knockoff", .plural = "knockoffs" },
    .{ .single = "handkerchief", .plural = "handkerchiefs" },
    .{ .single = "reed", .plural = "reeds" },
    .{ .single = "reef", .plural = "reefs" },
    .{ .single = "yourself", .plural = "yourselves" },
    .{ .single = "sunroof", .plural = "sunroofs" },
    .{ .single = "plateau", .plural = "plateaus" },
    .{ .single = "radius", .plural = "radii" },
    .{ .single = "stratum", .plural = "strata" },
    .{ .single = "stratus", .plural = "strati" },
    .{ .single = "focus", .plural = "foci" },
    .{ .single = "fungus", .plural = "fungi" },
    .{ .single = "appendix", .plural = "appendices" },
    .{ .single = "seraph", .plural = "seraphim" },
    .{ .single = "cherub", .plural = "cherubim" },
    .{ .single = "memo", .plural = "memos" },
    .{ .single = "cello", .plural = "cellos" },
    .{ .single = "automaton", .plural = "automata" },
    .{ .single = "button", .plural = "buttons" },
    .{ .single = "crayon", .plural = "crayons" },
    .{ .single = "captive", .plural = "captives" },
    .{ .single = "abrasive", .plural = "abrasives" },
    .{ .single = "archive", .plural = "archives" },
    .{ .single = "additive", .plural = "additives" },
    .{ .single = "hive", .plural = "hives" },
    .{ .single = "beehive", .plural = "beehives" },
    .{ .single = "olive", .plural = "olives" },
    .{ .single = "black olive", .plural = "black olives" },
    .{ .single = "chive", .plural = "chives" },
    .{ .single = "adjective", .plural = "adjectives" },
    .{ .single = "cattle drive", .plural = "cattle drives" },
    .{ .single = "explosive", .plural = "explosives" },
    .{ .single = "executive", .plural = "executives" },
    .{ .single = "negative", .plural = "negatives" },
    .{ .single = "fugitive", .plural = "fugitives" },
    .{ .single = "progressive", .plural = "progressives" },
    .{ .single = "laxative", .plural = "laxatives" },
    .{ .single = "incentive", .plural = "incentives" },
    .{ .single = "genesis", .plural = "geneses" },
    .{ .single = "surprise", .plural = "surprises" },
    .{ .single = "enterprise", .plural = "enterprises" },
    .{ .single = "relative", .plural = "relatives" },
    .{ .single = "positive", .plural = "positives" },
    .{ .single = "perspective", .plural = "perspectives" },
    .{ .single = "superlative", .plural = "superlatives" },
    .{ .single = "afterlife", .plural = "afterlives" },
    .{ .single = "native", .plural = "natives" },
    .{ .single = "detective", .plural = "detectives" },
    .{ .single = "collective", .plural = "collectives" },
    .{ .single = "lowlife", .plural = "lowlives" },
    .{ .single = "low-life", .plural = "low-lives" },
    .{ .single = "strife", .plural = "strifes" },
    .{ .single = "pony", .plural = "ponies" },
    .{ .single = "phony", .plural = "phonies" },
    .{ .single = "felony", .plural = "felonies" },
    .{ .single = "colony", .plural = "colonies" },
    .{ .single = "symphony", .plural = "symphonies" },
    .{ .single = "semicolony", .plural = "semicolonies" },
    .{ .single = "radiotelephony", .plural = "radiotelephonies" },
    .{ .single = "company", .plural = "companies" },
    .{ .single = "ceremony", .plural = "ceremonies" },
    .{ .single = "carnivore", .plural = "carnivores" },
    .{ .single = "emphasis", .plural = "emphases" },
    .{ .single = "abuse", .plural = "abuses" },
    .{ .single = "ass", .plural = "asses" },
    .{ .single = "mile", .plural = "miles" },
    .{ .single = "consensus", .plural = "consensuses" },
    .{ .single = "coatdress", .plural = "coatdresses" },
    .{ .single = "courthouse", .plural = "courthouses" },
    .{ .single = "playhouse", .plural = "playhouses" },
    .{ .single = "crispness", .plural = "crispnesses" },
    .{ .single = "racehorse", .plural = "racehorses" },
    .{ .single = "greatness", .plural = "greatnesses" },
    .{ .single = "demon", .plural = "demons" },
    .{ .single = "lemon", .plural = "lemons" },
    .{ .single = "pokemon", .plural = "pokemon" },
    .{ .single = "pokémon", .plural = "pokémon" },
    .{ .single = "christmas", .plural = "christmases" },
    .{ .single = "zymase", .plural = "zymases" },
    .{ .single = "accomplice", .plural = "accomplices" },
    .{ .single = "amice", .plural = "amices" },
    .{ .single = "titmouse", .plural = "titmice" },
    .{ .single = "slice", .plural = "slices" },
    .{ .single = "base", .plural = "bases" },
    .{ .single = "database", .plural = "databases" },
    .{ .single = "rise", .plural = "rises" },
    .{ .single = "uprise", .plural = "uprises" },
    .{ .single = "size", .plural = "sizes" },
    .{ .single = "prize", .plural = "prizes" },
    .{ .single = "booby", .plural = "boobies" },
    .{ .single = "hobby", .plural = "hobbies" },
    .{ .single = "baby", .plural = "babies" },
    .{ .single = "cookie", .plural = "cookies" },
    .{ .single = "budgie", .plural = "budgies" },
    .{ .single = "calorie", .plural = "calories" },
    .{ .single = "brownie", .plural = "brownies" },
    .{ .single = "lolly", .plural = "lollies" },
    .{ .single = "hippie", .plural = "hippies" },
    .{ .single = "smoothie", .plural = "smoothies" },
    .{ .single = "techie", .plural = "techies" },
    .{ .single = "specie", .plural = "species" },
    .{ .single = "quickie", .plural = "quickies" },
    .{ .single = "pixie", .plural = "pixies" },
    .{ .single = "rotisserie", .plural = "rotisseries" },
    .{ .single = "porkpie", .plural = "porkpies" },
    .{ .single = "newbie", .plural = "newbies" },
    .{ .single = "veggie", .plural = "veggies" },
    .{ .single = "bourgeoisie", .plural = "bourgeoisies" },
    .{ .single = "party", .plural = "parties" },
    .{ .single = "apology", .plural = "apologies" },
    .{ .single = "ancestry", .plural = "ancestries" },
    .{ .single = "anomaly", .plural = "anomalies" },
    .{ .single = "anniversary", .plural = "anniversaries" },
    .{ .single = "battery", .plural = "batteries" },
    .{ .single = "nappy", .plural = "nappies" },
    .{ .single = "hanky", .plural = "hankies" },
    .{ .single = "junkie", .plural = "junkies" },
    .{ .single = "hogtie", .plural = "hogties" },
    .{ .single = "footsie", .plural = "footsies" },
    .{ .single = "curry", .plural = "curries" },
    .{ .single = "fantasy", .plural = "fantasies" },
    .{ .single = "housefly", .plural = "houseflies" },
    .{ .single = "falsy", .plural = "falsies" },
    .{ .single = "doggy", .plural = "doggies" },
    .{ .single = "carny", .plural = "carnies" },
    .{ .single = "cabby", .plural = "cabbies" },
    .{ .single = "charlie", .plural = "charlies" },
    .{ .single = "bookie", .plural = "bookies" },
    .{ .single = "auntie", .plural = "aunties" },
    .{ .single = "constructor", .plural = "constructors" },
    .{ .single = "randomWord", .plural = "randomWords" },
    .{ .single = "camelCase", .plural = "camelCases" },
    .{ .single = "PascalCase", .plural = "PascalCases" },
    .{ .single = "Alumnus", .plural = "Alumni" },
    .{ .single = "CHICKEN", .plural = "CHICKENS" },
    .{ .single = "日本語", .plural = "日本語" },
    .{ .single = "한국", .plural = "한국" },
    .{ .single = "中文", .plural = "中文" },
    .{ .single = "اللغة العربية", .plural = "اللغة العربية" },
    .{ .single = "四 chicken", .plural = "四 chickens" },
    .{ .single = "Order2", .plural = "Order2s" },
    .{ .single = "Work Order2", .plural = "Work Order2s" },
    .{ .single = "SoundFX2", .plural = "SoundFX2s" },
    .{ .single = "oDonald", .plural = "oDonalds" },
};

test "basic pairs: plural, singular, and checks" {
    var p = try pl.Pluralize.init(t.allocator);
    defer p.deinit();

    for (pairs) |pair| {
        const got_plural = try p.plural(t.allocator, pair.single);
        defer t.allocator.free(got_plural);
        if (!std.mem.eql(u8, got_plural, pair.plural)) {
            std.debug.print("plural({s}) = {s}, want {s}\n", .{ pair.single, got_plural, pair.plural });
            return error.TestUnexpectedResult;
        }

        const got_single = try p.singular(t.allocator, pair.plural);
        defer t.allocator.free(got_single);
        if (!std.mem.eql(u8, got_single, pair.single)) {
            std.debug.print("singular({s}) = {s}, want {s}\n", .{ pair.plural, got_single, pair.single });
            return error.TestUnexpectedResult;
        }

        if (!p.isPlural(pair.plural)) {
            std.debug.print("isPlural({s}) = false\n", .{pair.plural});
            return error.TestUnexpectedResult;
        }
        if (!p.isSingular(pair.single)) {
            std.debug.print("isSingular({s}) = false\n", .{pair.single});
            return error.TestUnexpectedResult;
        }
    }
}

test "count picks singular or plural" {
    var p = try pl.Pluralize.init(t.allocator);
    defer p.deinit();

    for (pairs) |pair| {
        const as_count_1 = try p.count(t.allocator, pair.plural, 1, false);
        defer t.allocator.free(as_count_1);
        try t.expectEqualStrings(pair.single, as_count_1);

        const as_count_5 = try p.count(t.allocator, pair.single, 5, false);
        defer t.allocator.free(as_count_5);
        try t.expectEqualStrings(pair.plural, as_count_5);
    }
}

test "count inclusive prefixes the number" {
    var p = try pl.Pluralize.init(t.allocator);
    defer p.deinit();

    const got = try p.count(t.allocator, "test", 1, true);
    defer t.allocator.free(got);
    try t.expectEqualStrings("1 test", got);

    const got2 = try p.count(t.allocator, "test", 2, true);
    defer t.allocator.free(got2);
    try t.expectEqualStrings("2 tests", got2);
}

test "case preservation" {
    var p = try pl.Pluralize.init(t.allocator);
    defer p.deinit();

    const cases = [_][2][]const u8{
        .{ "cow", "cows" },
        .{ "Cow", "Cows" },
        .{ "COW", "COWS" },
    };
    for (cases) |c| {
        const got = try p.plural(t.allocator, c[0]);
        defer t.allocator.free(got);
        try t.expectEqualStrings(c[1], got);

        const back = try p.singular(t.allocator, c[1]);
        defer t.allocator.free(back);
        try t.expectEqualStrings(c[0], back);
    }
}

test "custom rules" {
    var p = try pl.Pluralize.init(t.allocator);
    defer p.deinit();

    // Irregular.
    try p.addIrregularRule("canadia", "canadensis");
    {
        const got = try p.plural(t.allocator, "canadia");
        defer t.allocator.free(got);
        try t.expectEqualStrings("canadensis", got);
    }
    {
        const got = try p.singular(t.allocator, "canadensis");
        defer t.allocator.free(got);
        try t.expectEqualStrings("canadia", got);
    }

    // Uncountable.
    try p.addUncountableRule("paper");
    {
        const got = try p.plural(t.allocator, "paper");
        defer t.allocator.free(got);
        try t.expectEqualStrings("paper", got);
    }

    // Plural rule.
    try p.addPluralRule("gex$", "gexii");
    {
        const got = try p.plural(t.allocator, "regex");
        defer t.allocator.free(got);
        try t.expectEqualStrings("regexii", got);
    }

    // Singular rule.
    try p.addSingularRule("s$", "");
    {
        const got = try p.singular(t.allocator, "appleS");
        defer t.allocator.free(got);
        try t.expectEqualStrings("apple", got);
    }
}
